postgresql:
  image: postgres:12
  container_name: load-generator-postgres
  ports:
    - "5421:5432"
  environment:
    - POSTGRES_DB=orchestrator
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=password
  networks: internal

orchestrator:
  image: edikgoose/orchestrator:latest
  container_name: orchestrator
  ports:
    - "8087:8087"
  networks: internal
  environment:
    - DB_URL=jdbc:postgresql://postgresql:5432/orchestrator
    - DB_USERNAME=postgres
    - DB_PASSWORD=password
    - CONSUL_URL=http://consul:8500
    - YANDEX_TANK_BASE_URL=http://tank-server:8888